### ISSUE TITLE
Extending CharacteristicType

### ISSUE THREAD

**Issue by tgu** [Bouke/HAP#45]
I am implementing a custom outlet accessory that measures both power and energy. For that reason `CharacteristicType` is extended with `.watt` and `. kiloWattHour`. Since there is no way to extend an enum this has to be done in the HAP library. It would however be desirable if you could avoid creating custom versions of the library, especially since I am using the proprietary characteristics and their UUIDs used by Elgato Eve, partly documented by [gomfunkel](https://gist.github.com/gomfunkel/b1a046d729757120907c). This way the energy sensor shows up in their app. 
 ```
extension Accessory {
    open class Energy: Accessory {
        public let energy = Service.Energy()
        
        public init(info: Service.Info) {
            super.init(info: info, type: .outlet, services: [energy])
        }
    }
}

extension Service {
    open class Energy: Service {
        public let on = GenericCharacteristic<Bool>(type: .on, value: false)
        public let inUse = GenericCharacteristic<Bool>(type: .outletInUse, value: true, permissions: [.read, .events])
        public let watt = GenericCharacteristic<Double>(type: .watt, value: 0, permissions: [.read, .events])
        public let kiloWattHour = GenericCharacteristic<Double>(type: .kiloWattHour, value: 0, permissions: [.read, .events])
        
        public init() {
            super.init(type: .outlet, characteristics: [on, inUse, watt, kiloWattHour])
        }
    }
}
```

Another problem is that `Accessory.init` seems to be internal and cannot be called outside the library, changing the permission opens a can of worms.

**Comment by Bouke** [comment]
The `CharacteristicType` as defined by Apple has some-predefined values, some of them have been included in this project. The HAP standard also allows you to specify custom types, which is what Eve (vendor) has been doing. It is currently in the Swift language not possible to extend an enum with additional cases. So we would then either need to change the enum to support associated values, or move away from the enum design altogether.

[`Accessory.init`][0] is `public`, so that should be callable from your code.

[0]: https://github.com/Bouke/HAP/blob/46d668360a3bd6a4c9165bc9864b7afe05be1589/Sources/HAP/Base/Accessory.swift#L86

**Comment by tgu** [comment]
swift evolution [proposal 0192](https://github.com/apple/swift-evolution/blob/master/proposals/0192-non-exhaustive-enums.md#can-there-be-a-kind-of-open-enum-where-you-can-add-new-cases-in-extensions) last paragraph states that 

> There is no push to allow adding new cases to an enum from outside a library.


My mistake, it is [Service.init](https://github.com/Bouke/HAP/blob/46d668360a3bd6a4c9165bc9864b7afe05be1589/Sources/HAP/Base/Service.swift#L35) that is internal. If you make that public you also need to make some more entities public.
