### ISSUE TITLE
Cannot add >23 accessories to bridge

### ISSUE THREAD

**Issue by Bouke** [Bouke/HAP#57]
Danny reached out to me by e-mail with an issue not being able to add >23 accessories, which I confirmed on my end as well.

> The one with 23 items, the size is: 15,744 bytes
>
>     [hap.endpoints|INFO] 192.168.1.214 GET /accessories - 200 15744

> The one with 24 items, the size is: 16,344 bytes
>
>     [hap.endpoints|INFO] 192.168.1.214 GET /accessories - 200 16344

The error showing up in the server's logs is:

    [hap.http|ERROR] Error while reading from socket [ERROR: Error code: -9971(0x-26F3), Connection reset by peer]

**Comment by dmavromatis** [comment]
I have been able to reproduce having the error of, "Connection reset by peer" if I pass in an improper length and write... so I suspect the issue is based on content size over ~16k?  Not sure how to troubleshoot this, but one idea to narrow down content size issue, is to test length issue by adding 23 items and using long names and serial numbers to try to break it with 23 that is known to work.

`
let length = UInt16(data.count).bigEndian.bytes
logger.debug("Message: \(data.hex), Nonce: \(nonce.hex), Length: \(length.hex)")
let encrypted = try ChaCha20Poly1305.encrypt(message: data,
                                                     additional: length,
                                                     nonce: nonce,
                                                     key: encryptKey)
`

**Comment by dmavromatis** [comment]
Update - confirmed related to 16384 Bytes issue...

This does not work (you can see the WriteBuffer is 16388, 4 bytes over):
`[hap.endpoints|INFO] 172.20.10.1 GET /accessories - 200 16310`

`WriteBuffer 16388: Optional("HTTP/1.1 200 OK\r\nContent-Type: application/hap+json\r\nContent-Length: 16310`

This works (you can see the WriteBuffer is 16161): 
`[hap.endpoints|INFO] 172.20.10.1 GET /accessories - 200 16083`

`WriteBuffer 16161: Optional("HTTP/1.1 200 OK\r\nContent-Type: application/hap+json\r\nContent-Length: 16083`

**Comment by Bouke** [comment]
I'm not sure why this issue manifested at messages exceeding 16k, as messages exceeding 1k are already in violation of the specs.

Messages from the controller should also adhere to this spec, however the old implementation had a `precondition` (trap) that would be hit if messages were split. I haven't come across a situation where the controller sends such large messages. Anyway that should be fixed now too, although I haven't found a way to test this from an actual iOS device.

Thanks for the input!

**Comment by dmavromatis** [comment]
Confirmed -- it works here as well.
